export const GET_LIST_TASKS = 'GET_LIST_TASKS';

export const GET_LIST_TASKS_REQUEST = 'GET_LIST_TASKS/pending';
export const GET_LIST_TASKS_SUCCESS = 'GET_LIST_TASKS/fulfilled';
export const GET_LIST_TASKS_FAILURE = 'GET_LIST_TASKS/failed';

export const ADD_LIST_TASK = 'ADD_LIST_TASK';

export const ADD_LIST_TASK_REQUEST = 'ADD_LIST_TASK/pending';
export const ADD_LIST_TASK_SUCCESS = 'ADD_LIST_TASK/fulfilled';
export const ADD_LIST_TASK_FAILURE = 'ADD_LIST_TASK/failed';

export const REMOVE_LIST_TASK = 'REMOVE_LIST_TASK';

export const REMOVE_LIST_TASK_REQUEST = 'REMOVE_LIST_TASK/pending';
export const REMOVE_LIST_TASK_SUCCESS = 'REMOVE_LIST_TASK/fulfilled';
export const REMOVE_LIST_TASK_FAILURE = 'REMOVE_LIST_TASK/rejected';

export const UPDATE_LIST_TASK = 'UPDATE_LIST_TASK';

export const UPDATE_LIST_TASK_REQUEST = 'UPDATE_LIST_TASK/pending';
export const UPDATE_LIST_TASK_SUCCESS = 'UPDATE_LIST_TASK/fulfilled';
export const UPDATE_LIST_TASK_FAILURE = 'UPDATE_LIST_TASK/failed';

export const DELETE_CHECKED_LIST_TASKS = 'DELETE_CHECKED_LIST_TASKS';

export const DELETE_CHECKED_LIST_TASKS_REQUEST = 'DELETE_CHECKED_LIST_TASKS/pending';
export const DELETE_CHECKED_LIST_TASKS_SUCCESS = 'DELETE_CHECKED_LIST_TASKS/fulfilled';
export const DELETE_CHECKED_LIST_TASKS_FAILURE = 'DELETE_CHECKED_LIST_TASKS/rejected';
